---
on:
  push:
    branches:
      - "*"
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@just

      - name: Install dependencies
        run: |
          sudo apt install -y podman qemu-user-static lrzip
          sudo systemctl start systemd-binfmt.service

      - name: Create rootfs
        run: just build-jetson-rootfs

      - name: Build jetson image for Jetson nano revision 300
        run: |
          just build-jetson-image  \
            jetson-nano \
            300

      - name: Build jetson image for Jetson nano revision 200
        run: |
          just build-jetson-image \
            jetson-nano \
            200

      - name: Build jetson image for Jetson nano 2G
        run: |
          just build-jetson-image \
            jetson-nano-2gb
