---
on:
  push:
    tags:
      - "*"
name: Build
env:
  BSP: 32.7.4
  UBUNTU: 20.04
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just

      - name: Install dependencies
        run: |
          sudo apt install -y podman qemu-user-static lrzip
          sudo systemctl start systemd-binfmt.service

      - name: Create rootfs
        run: just build-jetson-rootfs

      - name: Build jetson image for Jetson nano revision 300
        run: |
          sudo -E just build-jetson-image  \
            jetson-nano \
            300
          sudo mv jetson.img "jetson-nano-300_$UBUNTU_$BSP.img"
          sudo lrzip "jetson-nano-300_$UBUNTU_$BSP.img"
          sudo rm -rf "jetson-nano-300_$UBUNTU_$BSP.img"
          ls -lht "jetson-nano-300_$UBUNTU_$BSP.img.lrz"

      - name: Build jetson image for Jetson nano revision 200
        run: |
          sudo -E just build-jetson-image \
            jetson-nano \
            200
          sudo mv jetson.img "jetson-nano-200_$UBUNTU_$BSP.img"
          sudo lrzip "jetson-nano-200_$UBUNTU_$BSP.img"
          sudo rm -rf "jetson-nano-200_$UBUNTU_$BSP.img"
          ls -lht "jetson-nano-200_$UBUNTU_$BSP.img.lrz"

      - name: Build jetson image for Jetson nano 2G
        run: |
          sudo -E just build-jetson-image \
            jetson-nano-2gb
          sudo mv jetson.img "jetson-nano-2gb_$UBUNTU_$BSP.img"
          sudo lrzip "jetson-nano-2gb_$UBUNTU_$BSP.img"
          sudo rm -rf "jetson-nano-2gb_$UBUNTU_$BSP.img"
          ls -lht "jetson-nano-2gb_$UBUNTU_$BSP.img.lrz"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            [CHANGELOG.md](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md)
          files: "jetson*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
